services:
  postgres:
      container_name: postgresql
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      
      volumes:
        - ./postgres-db:/var/lib/postgresql/data
      ports:
        - '5432:5432'
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'"]
        interval: 10s
        timeout: 3s
        retries: 3
        
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-cache-data:/data

  celery:
    image: samirul08/youcloud
    restart: always
    command: celery -A youcloud worker --pool=solo -l info
    volumes:
      - .:/youcloud-app
      - static:/vol/web/static 
      - media:/vol/web/media 
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - gunicorn
      - cache

  gunicorn:
    image: samirul08/youcloud
    restart: always
    ports:
      - 8000:8000
    env_file:
      - path: ".env"
    volumes:
      - static:/vol/web/static
      - media:/vol/web/media
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - static:/vol/web/static
      - media:/vol/web/media
    ports:
      - "80:80"
    depends_on:
      - gunicorn

volumes:
  postgres-db:
  redis-cache-data:
  static:
  media:


