# Generated by Django 5.0.2 on 2024-03-01 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YtMusicFiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("downloaded_url_video_link", models.CharField(max_length=255)),
                ("downloaded_music_files", models.FileField(upload_to="youtube_files")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
