# Generated by Django 5.0.2 on 2024-03-11 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ytmusicfiles",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ytmusicfiles",
            name="downloaded_music_files",
            field=models.FileField(blank=True, null=True, upload_to="youtube_files"),
        ),
        migrations.AlterField(
            model_name="ytmusicfiles",
            name="downloaded_music_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ytmusicfiles",
            name="downloaded_url_video_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
