# Generated by Django 5.0.2 on 2024-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_ytmusicfiles_downloaded_music_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ytmusicfiles",
            name="downloaded_music_files",
            field=models.FileField(upload_to=""),
        ),
    ]
