# Generated by Django 5.0.2 on 2024-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(blank=True, null=True, upload_to="profile-pic"),
        ),
    ]
