name: Build Code


on: [push, pull_request]

jobs:
  build:
    environment:
      name: Testing youcloud Code using pytest

    env:
      DATABASE_NAME: ${{secrets.YOUCLOUD_DATABASE_NAME}}
      DATABASE_USER: ${{secrets.YOUCLOUD_DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.YOUCLOUD_DATABASE_PASSWORD}}
      DATABASE_HOST: ${{secrets.YOUCLOUD_DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.YOUCLOUD_DATABASE_PORT}}
      DJANGO_SECRET_KEY: ${{secrets.YOUCLOUD_SECRET_KEY}}
      DJANGO_SIGNING_KEY: ${{secrets.YOUCLOUD_SIGNING_KEY}}
      GOOGLE_SOCIAL_LOGIN_CLIENT_ID: ${{secrets.GOOGLE_SOCIAL_LOGIN_CLIENT_ID}}
      GOOGLE_SOCIAL_LOGIN_SECRET_KEY: ${{secrets.GOOGLE_SOCIAL_LOGIN_SECRET_KEY}}
      GOOGLE_CODE: ${{secrets.GOOGLE_CODE}}
      CELERY_BROKER_URL_LINK: ${{secrets.CELERY_BROKER_URL_LINK}}
      CELERY_TIMEZONE_PLACE: ${{secrets.CELERY_TIMEZONE_PLACE}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.YOUCLOUD_DATABASE_USER}}
          POSTGRES_PASSWORD: ${{secrets.YOUCLOUD_DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.YOUCLOUD_DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest
    steps:
      - name: pulling codes from repository
        uses: actions/checkout@v4.1.6

      - name: Install python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11.4'

      - name: Using redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'
          number of databases: 100
    
      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
      
      - name: update pip
        run: python -m pip install --upgrade pip

      - name: Install all the dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Copy Fixed Version cipher.py
        run: |
          cd /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pytube
          ls -a
          cp /home/runner/work/youcloud/youcloud/cipher.py /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pytube/
          ls -a 
          cp /home/runner/work/youcloud/youcloud/cipher.py /opt/hostedtoolcache/Python/3.11.4/x64/bin/python/site-packages/pytube/
          ls -a 
      
      - name: Automate test codes with pytest
        run: |
          pip install pytest
          pytest -v -s