name: Deploying to vps

on:
  workflow_run:
    workflows: ["Pushing to dockerhub"]
    types:
        - completed
jobs:
  build:
    name: Deploying container to vps

    runs-on: ubuntu-latest
    steps:
      - name: Login to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.VPS_IP }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.VPS_PASSWORD }}
            script: |
                git clone git@github.com:samirul/youcloud.git
                cd /home/ubuntu/youcloud/
                git pull git@github.com:samirul/youcloud.git
                cp /home/ubuntu/youcloud-env/.env /home/ubuntu/youcloud/
                sudo docker rm -f youcloud-gunicorn-1 || true
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/youcloud:latest
                docker compose -f docker-compose_prod.yml up -d --build