name: Deploying to vps

on:
  workflow_run:
    workflows: ["Pushing to dockerhub"]
    types:
        - completed
jobs:
  build:
    name: Deploying container to vps

    runs-on: ubuntu-latest
    steps:
      - name: Login to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.VPS_IP }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.VPS_PASSWORD }}
            script: |
                mkdir youcloud
                cp dockercompose_prod.yml /youcloud/
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/youcloud:latest
                cd youcloud
                docker compose -f dockercompose_prod.yml up -d --build