name: Pushing to dockerhub

on: [push]

jobs:
  build:
    environment:
      name: Pushing youcloud project image to dockerhub
    env:
      DATABASE_NAME: ${{secrets.YOUCLOUD_DATABASE_NAME}}
      DATABASE_USER: ${{secrets.YOUCLOUD_DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.YOUCLOUD_DATABASE_PASSWORD}}
      DATABASE_HOST: ${{secrets.YOUCLOUD_DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.YOUCLOUD_DATABASE_PORT}}
      DJANGO_SECRET_KEY: ${{secrets.YOUCLOUD_SECRET_KEY}}
      DJANGO_SIGNING_KEY: ${{secrets.YOUCLOUD_SIGNING_KEY}}
      DEBUG: ${{secrets.DEBUG}}
      DJANGO_ALLOWED_HOSTS: ${{secrets.DJANGO_ALLOWED_HOSTS}}
      EMAIL_USER: ${{secrets.EMAIL_USER}}
      EMAIL_PASS: ${{secrets.EMAIL_PASS}}
      GOOGLE_SOCIAL_LOGIN_CLIENT_ID: ${{secrets.GOOGLE_SOCIAL_LOGIN_CLIENT_ID}}
      GOOGLE_CODE: ${{secrets.GOOGLE_CODE}}
      CELERY_BROKER_URL_LINK: ${{secrets.CELERY_BROKER_URL_LINK}}
      CELERY_TIMEZONE_PLACE: ${{secrets.CELERY_TIMEZONE_PLACE}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling codes from repository
        uses: actions/checkout@v4.1.6
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image in dockerhub
        run: |
          docker build -t samirul08/youcloud:latest
          docker push samirul08/youcloud:latest